%YAML:1.0
LeftTopX: 0
LeftTopY: 4
RightTopX: 7726
RightTopY: 5
LeftBottomX: 6
LeftBottomY: 5360
RightBottomX: 7719
RightBottomY: 5360
LensNumX: 542
LensNumY: 434
FocalLength: 0.00978
MLAFocalLength: 0.000036
WhiteBalanceR: 1.0
WhiteBalanceG: 0.7
WhiteBalanceB: 0.8
